### ISSUE TITLE
上传报错，提示fs_1.default.rm is not a function

### ISSUE THREAD

**Issue by rebron1900** [jinzhi0123/picgo-plugin-alist#1]
![image](https://user-images.githubusercontent.com/7929884/194994432-01669680-8bcc-4a77-82a8-eb954a5d10b9.png)

![image](https://user-images.githubusercontent.com/7929884/194994490-e43259b1-c3bf-42e5-a3dc-f6ee40406ccb.png)

**Comment by jinzhi0123** [comment]
您的picgo和插件版本是多少呢？
您可以尝试更新一下picgo版本到最新版本（这似乎是有效的）
