### ISSUE TITLE
上传图片后无法正常显示

### ISSUE THREAD

**Issue by ikale** [jinzhi0123/picgo-plugin-alist#18]
感谢开发者无私的分享。
如题，图片是已经成功上传到了网盘指定目录中的，alist中的url地址和图床内的url地址是不一致，这个是否还需要额外配置才行呢，文档中好像并没有额外的说明了。
最后，里面原有图片怎么显示出来。

**Comment by at2008** [comment]
同样的问题，上传正常，alist中显示正常，picgo的相册里面无法显示，拷贝地址正常！

**Comment by SkysCrystal** [comment]
内嵌图片必须使用alist里头的 download 链接，我目前的问题是 picgo 生成的图片链接不正确，没有 `?sign=axxxxxxx` 这部分，
访问提示： 
`{"code":401,"message":"expire missing","data":null}`

**Comment by jinzhi0123** [comment]
alist新版本更新了签名，解决方案可以在仓库页readme查看。
