### ISSUE TITLE
上传成功，但picgo给的链接与alist里复制的链接不同。

### ISSUE THREAD

**Issue by yangzheng6678** [jinzhi0123/picgo-plugin-alist#19]
如题，alist复制的链接后面有?sign=n0ELUKtu3RZlhvtQCmaJDaoPaXkKCkgJja_GLX0_RzE=:0，而picgo给的链接没有，导致不能使用。

**Comment by jinzhi0123** [comment]
alist新版本更新了签名，解决方案可以在仓库页readme查看。
