### ISSUE TITLE
上传报错，提示：EPERM: operation not permitted, open './child-817373_1920_(1).jpg'    

### ISSUE THREAD

**Issue by mofanx** [jinzhi0123/picgo-plugin-alist#2]
![image](https://user-images.githubusercontent.com/93850573/195075681-9f95cc6d-e93f-49a9-affa-5a7b534fa119.png)
![image](https://user-images.githubusercontent.com/93850573/195075838-b2a8662a-c5e5-4cbd-a6cf-0e64fc5e6111.png)
之前还出现过一次：上传报错，提示fs_1.default.rm is not a function。
更新到最新beta版后，还是一直显示 EPERM: operation not permitted。
求大佬解答！

**Comment by mofanx** [comment]
之前还出现过一次：上传报错，提示fs_1.default.rm is not a function

**Comment by mofanx** [comment]
嗯嗯，我更新到最新版本后，终于成功了！但是有个地方需要注意下，可能alist v3的管理员token获取渠道，发生了变化，我用localStorage中的admin-token没有成功，虽然picgo会显示上传成功，但实际并没有真正上传，日志会显示"that's not even a token\"，最后，我是使用localStorage中admin-token下面拥有更长字符串的token，才成功的。希望大家可以注意下，再次感谢大佬开发这么好用的插件！
![image](https://user-images.githubusercontent.com/93850573/195240927-8b464a36-25a4-4016-abe4-d22b68af2a68.png)

**Comment by jinzhi0123** [comment]
感谢支持
