### ISSUE TITLE
文件流量和访问速度，还有费用是受限于alist所在服务器对吧？

### ISSUE THREAD

**Issue by Index103000** [jinzhi0123/picgo-plugin-alist#24]
配置完成后，图片的地址就是 alist 的访问地址对吧，也就是买的服务器地址，那么流量是不是也是走你服务器的流量？有什么其他方法可以直接走云盘自身流量吗？

**Comment by jinzhi0123** [comment]
链接会被302重定向到源地址，也就是说alist服务器只负责资源定向（不会有图片本身的流量），图片本身的流量会从源地址走。
