### ISSUE TITLE
无论V2还是v3都会添加/d//这个 字符

### ISSUE THREAD

**Issue by TurkeyD** [jinzhi0123/picgo-plugin-alist#4]
使用的是这个版本
![image](https://user-images.githubusercontent.com/69117862/196027969-990d6a61-c69e-449b-9df3-9c4ecf9f1c25.png)
可以显示上传成功    
![image](https://user-images.githubusercontent.com/69117862/196027891-563ec983-e9fd-460d-8036-865f63a6f842.png)
但是无论V2还是v3都会添加/d//这个 字符
导致最终失败 
![image](https://user-images.githubusercontent.com/69117862/196027824-79c766fa-13d0-4ea8-8f2f-9a1c80951e46.png)
请问 这个/d//这个怎么去掉  要不然这个路径总是错误

我还去问了下picgo的作者 。。。他让我来问您这边
![image](https://user-images.githubusercontent.com/69117862/196035827-88ec0a98-395f-41f0-bf7f-285ec1e2dc66.png)

**Comment by jinzhi0123** [comment]
这个“/d//”没有问题的。您可以检查根目录下是不是没有挂载网盘（而是挂载到了其他路径，如https://xxx.com/onedrive，在picgo的配置项path中填写onedrive）。

**Comment by xiaojieen** [comment]
我的也是这样

**Comment by jinzhi0123** [comment]
请检查配置项中的“上传路径”，默认上传至根目录，请确保根目录有挂载存储，如果存储挂载到别的路径，那就在“上传路径”中填写对应路径。”/d/“是alist获取直链的路径。

**Comment by SkysCrystal** [comment]
图片正常上传，但是复制的图片地址会变成： `alist地址/d/上传路径` 多一个 d 出来，删掉 d/ 图片正常访问。

**Comment by yangzheng6678** [comment]
我的也是这样，生成的连接去掉/d就能用
