### ISSUE TITLE
试了N多次，还是不死心。。。

### ISSUE THREAD

**Issue by kevzcr** [jinzhi0123/picgo-plugin-alist#8]
![image](https://user-images.githubusercontent.com/88956040/198466026-0465720c-c792-40d3-ba12-168508571c18.png)
我知道填写的不对，但怎么才能填对呢？
![image](https://user-images.githubusercontent.com/88956040/198467197-033a3c73-a174-4e10-a44d-f11e9d6cd03f.png)
获取token的方法也不知道正确不？
经历过成功配置插件如picgo-plugin-NutStore，picgo-plugin-rclone,   github  , smms等，每一种都失败过N多次，这次却感觉完全找不到北，太难了，大佬，救命呀。

**Comment by jinzhi0123** [comment]
你的alist地址为http://127.0.0.1:5244/11 这里的'/11'是什么呢
另外可以提供一下报错和picgo日志

**Comment by kevzcr** [comment]
> `11` 是我给加载的onedrive盘起的名字。

![image](https://user-images.githubusercontent.com/88956040/198591240-7ff4f3c0-ab04-464c-8468-8525ec68064c.png)

> 成功了，感谢您的回复 ，发现其实是我一直被通知所误导了，图片已经传到onedrive中了，而通知却报错。
![image](https://user-images.githubusercontent.com/88956040/198594757-ee1c355b-14f7-4a49-802e-62d977a80902.png)
> 通知的报错率百分之百。。。。 汗。。。  多亏今天看了一下网盘，否则还在艰苦探索中。。。
![image](https://user-images.githubusercontent.com/88956040/198595864-d290480a-39e5-4f57-80c2-49c30b0f0b9b.png)
问题：
1.日志是我复制粘贴到这里，对吧？我想让你帮我看看问题出在哪。不能看到上传成功几个字，强迫症表示忍不了。
2.有隐私泄露的可能吗？因为我从不看日志（不懂里面说什么）。
3.文件名命名规则在哪里修改，比如我想用原始文件名（但剪贴板中的图片如何命名呢）
- 还有问题，但先解决了通知再说。顺便再上传一张即时截图，开心一下。。。。
![image](https://user-images.githubusercontent.com/88956040/198603706-c8f364fe-ce3e-4e7d-9d7c-52a4f1db117c.png)

**Comment by kevzcr** [comment]
补充一下，利用CloudDriveService  加载onedrive，会有一个问题，文件更新不及时，图片上传后，当时在加载的网盘中是看不到（要过会才行），这就是我的这次的问题所在。我一直盯着加载的网盘看，一直没看到我想看到的图片上传结果，打开onedrive网页才发现图片已乖乖地躺在那里了。。。

**Comment by kevzcr** [comment]
改用rclone加载onedrive，就好多了，从出现报错通知开始，大概5秒左右就能看到网盘中多出来的图片了。

![image](https://user-images.githubusercontent.com/88956040/198615882-7ddb3bd6-40f4-47e6-9b8d-2c9d3d5a17e0.png)

**Comment by jinzhi0123** [comment]
请更新最新版本插件噢。更新后应该就不会报错了。
文件名称由PicGo控制，可以开启"文件重命名"功能，这样在上传前会弹出对话框以重命名文件。可以参考：https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E4%B8%8A%E4%BC%A0%E5%89%8D%E9%87%8D%E5%91%BD%E5%90%8D
插件的日志信息没有隐私信息（如果你不想贴出图片地址的话可以打个码），如果要提供日志信息的话提供最后那一段就可以了。

**Comment by kevzcr** [comment]
- 22.10.29日志   使用 `PicGo-core`  (非图形界面PicGo)
- 其中日志第八行 
- `请求结果` 处内容和PicGo软件上传报错内容完全一致，好在使用PicGo-core是没有通知的。

> 2022-10-29 08:17:58 [PicGo INFO] Before transform 
2022-10-29 08:17:58 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-29 08:17:58 [PicGo INFO] Before upload 
2022-10-29 08:17:58 [PicGo INFO] Uploading... Current uploader is [alist] 
2022-10-29 08:17:58 [PicGo INFO] [信息]version:3,path:/6/Apps/pic1029,fileName:壁纸.jpg,url:http://127.0.0.1:5244 
2022-10-29 08:17:58 [PicGo INFO] [信息]已经写入文件C:\Users\D\AppData\Local\Temp\壁纸.jpg 
2022-10-29 08:18:02 [PicGo INFO] [请求结果]"{\"code\":200,\"message\":\"success\",\"data\":null}" 
2022-10-29 08:18:02 [PicGo SUCCESS] 
http://127.0.0.1:5244/d//6/Apps/pic1029/%E5%A3%81%E7%BA%B8.jpg 

我使用的PicGo版本为正式版最新版（非bata版）。
- 问题：我需要升级到bata版吗？
- 
![image](https://user-images.githubusercontent.com/88956040/198754442-5ab83d15-b4ac-4d61-b538-110478429f9a.png)

**Comment by kevzcr** [comment]
![image](https://user-images.githubusercontent.com/88956040/198754592-a32265ee-9f70-46d9-bebe-0efaf2739ff4.png)

**Comment by jinzhi0123** [comment]
插件更新方法：
![Snipaste_2022-10-29_10-38-49](https://user-images.githubusercontent.com/88891480/198784121-a5de3b7d-c03f-46c9-846c-288c8316ef4e.png)
alist V3本身可以同步两个网盘

**Comment by kevzcr** [comment]
已更新
![image](https://user-images.githubusercontent.com/88956040/198813675-f813a8a4-1291-4623-9b20-778c31bae000.png)
新问题请教： Typora PicGo-core插件报错，无法上传
![image](https://user-images.githubusercontent.com/88956040/198813823-fba586ea-a58a-4c7d-9343-497674ada23c.png)
我直接运行 `picgo u`命令  是可以上传的。

**Comment by kevzcr** [comment]
> alist V3本身可以同步两个网盘

能大概讲一下乍操作吗？谢谢。

**Comment by kevzcr** [comment]
刚在AList 管理中 看了半天，一头雾水，是元信息栏吗？

**Comment by jinzhi0123** [comment]
typora中带的picgo-core版本过低，部分API已经废弃。
可以全局安装picgo（npm install -g picgo ，当然也可以局部安装然后指定路径），然后在typora中使用自定义指令即可
![image](https://user-images.githubusercontent.com/88891480/198816385-7e69abba-0af3-42c7-bb50-7a89af7b240b.png)
alist v3可以跨网盘复制（当然这可能不太符合你想要自动同步的需求）。之后会考虑添加同时上传至两个路径的功能。

**Comment by zuojinxin** [comment]
![未命名图片](https://user-images.githubusercontent.com/118601868/202926707-0ea3bb37-4fb7-45f2-ae7b-fb7a792ba812.png)
我这个哪里设置有问题吗，一直报错

**Comment by zuojinxin** [comment]
Error: ϵͳ�Ҳ���ָ����·����

    at notFoundError (C:\Users\zjx\AppData\Roaming\picgo\node_modules\exec-buffer\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\zjx\AppData\Roaming\picgo\node_modules\exec-buffer\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\zjx\AppData\Roaming\picgo\node_modules\exec-buffer\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
这个是报错提示的

**Comment by zuojinxin** [comment]
又可以了 放了一天没管 莫名其妙就好了
