### ISSUE TITLE
无法做图床

### ISSUE THREAD

**Issue by kevzcr** [jinzhi0123/picgo-plugin-alist#9]
上传的图片要是能在别处引用就好了。

**Comment by jinzhi0123** [comment]
上传完成后会自动复制图片链接（alist对应的地址）到剪贴板。
alist会对链接地址做302重定向到网盘直链（这无法避免，因为很多网盘的直链都是会变化的），各种应用场景对这种302重定向的方式支持不同，目前已知HTML网页和typora等markdown编辑器等对此是支持的。
